#!/usr/bin/env python3
import argparse
import string
import secrets


def generate_password(length, chars):
    if length < 12:
        return("Minimum length is 12 characters")
    new_password = ""
    for _ in range(length):
        random_char = secrets.choice(chars)
        new_password += random_char
    return new_password


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Outputs a password of the given length"
    )

    parser.add_argument("-l", "--length", type=int, default=12, help="Specify length")
    parser.add_argument(
        "-s",
        "--special_characters",
        type=str,
        default="!@#$%^&*",
        help="Specify special characters that are wrapped in single quotes. Single quotes ensure the characters are interpeted literally",
    )
    args = parser.parse_args()

    chars = (
        string.ascii_uppercase
        + string.ascii_lowercase
        + string.digits
        + args.special_characters
    )

    password = generate_password(args.length, chars)
    print(password)
